# Generated by Django 4.0.4 on 2022-05-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_as_markdown",
                    models.BooleanField(
                        default=False, verbose_name="As markdown"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        default="no_image.svg",
                        max_length=25,
                        verbose_name="Cover",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="Title"),
                ),
                (
                    "preamble",
                    models.CharField(max_length=1024, verbose_name="Preamble"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, null=True, verbose_name="Body"
                    ),
                ),
                (
                    "body_as_markdown",
                    models.BooleanField(
                        default=False, verbose_name="As markdown"
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "num",
                    models.PositiveIntegerField(verbose_name="Lesson number"),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_as_markdown",
                    models.BooleanField(
                        default=False, verbose_name="As markdown"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ("course", "num"),
            },
        ),
        migrations.CreateModel(
            name="CoursesTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name_first",
                    models.CharField(max_length=128, verbose_name="Name"),
                ),
                (
                    "name_second",
                    models.CharField(max_length=128, verbose_name="Surname"),
                ),
                ("day_birth", models.DateField(verbose_name="Birth date")),
                ("courses", models.ManyToManyField(to="mainapp.course")),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
